# Generated by Django 4.2.15 on 2024-09-14 05:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_ussa_supplier_remove_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cek',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 14)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 14)),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.category'),
        ),
    ]
