# Generated by Django 4.2.15 on 2024-09-14 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('company', '0003_alter_cek_date_alter_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='initial_price_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gelen_pul_birligi', to='common.currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satys_pul_birligi', to='common.currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.unit'),
        ),
    ]
