# Generated by Django 4.2.15 on 2024-09-19 06:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_product_initial_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cek',
            name='reference_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cek',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.cek'),
        ),
        migrations.AlterField(
            model_name='cek',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 19)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 19)),
        ),
    ]
