# Generated by Django 4.2.15 on 2024-09-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_cek_reference_percentage_payment_cek_alter_cek_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cek',
            options={'ordering': ['-updated_at', '-date']},
        ),
        migrations.AddField(
            model_name='cek',
            name='reference_comission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cek',
            name='cek_type',
            field=models.CharField(choices=[('SATYN_ALYS', 'Satyn Alyş Çegi'), ('SATYS', 'Satyş Çegi')], max_length=255),
        ),
    ]
